kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: default
      containers:
      - image: registry.ash.tv/admin/api
        name: api
        imagePullPolicy: Always
        ports:
        - name: api-port
          containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - name: http
    targetPort: api-port
    port: 8080
  selector:
    app: api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: api.infrash.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 8080
