apiVersion: v1
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "DEBUG"
    debug = true
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entrypoints.http.redirect]
        entryPoint = "https"
      compress = true
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
      [entryPoints.traefik]
      address = ":8080"
    [kubernetes]
    [traefikLog]
      format = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
    [acme]
    email = ""
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
     [acme.dnsChallenge]
       provider = "digitalocean"
       delayBeforeCheck = 0
    [[acme.domains]]
      main = "*.infrash.tech"
      sans = ["infrash.tech"] 
kind: ConfigMap
metadata:
  creationTimestamp: 2018-11-29T15:31:39Z
  labels:
    app: traefik
    chart: traefik-1.54.0
    heritage: Tiller
    release: wrinkled-narwhal
  name: wrinkled-narwhal-traefik
  namespace: default
  resourceVersion: "990"
  selfLink: /api/v1/namespaces/default/configmaps/wrinkled-narwhal-traefik
  uid: dd857af4-f3eb-11e8-a2eb-6e10fea98efe
